# Generated by Django 3.2.18 on 2023-05-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=0)),
                ('voltage', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
            ],
        ),
    ]
